include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_dynamic_calls: true
    avoid_field_initializers_in_const_classes: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    cast_nullable_to_non_nullable: true
    close_sinks: true
    deprecated_consistency: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    noop_primitive_operations: true
    only_throw_errors: true
    throw_in_finally: true
    unawaited_futures: true
    unnecessary_statements: true
    unnecessary_await_in_return: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    tighten_type_of_initializing_formals: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    use_colored_box: true
    use_decorated_box: true

analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
    prefer_for_elements_to_map_fromiterable: ignore
  exclude:
    - "**.mocks.dart"
    - "**.g.dart"
    - "**.freezed.dart"
    - "lib/generated/**"
    - "lib/injectable/injectable.config.dart"